<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A listing will not be approved if it has application URLs or an email alias within the description. All students should apply for this job through StudentHub' => '',
    'Amount Due' => '',
    'Buy Credit' => '',
    'Cost Per Applicant' => '',
    'Current Credit' => '',
    'Decide carefully! You may not be able to change these questions without contacting us once you publish your job posting' => '',
    'Draft' => '',
    'Filter students by Degree' => '',
    'Filter students by English Level' => '',
    'Filter students by GPA' => '',
    'Filter students by Graduation Year' => '',
    'Filter students by Language Spoken' => '',
    'Filter students by Major' => '',
    'Filter students by Nationality' => '',
    'Have a question for the applicants? (optional)' => '',
    'Industry' => '',
    'Languages' => '',
    'Leave blank to show "flexible start date"' => '',
    'Listing Cost' => '',
    'Majors' => '',
    'Make Payment' => '',
    'Max Applicants' => '',
    'Maximum Number of Applicants' => '',
    'Minimum 10' => '',
    'Nationalities' => '',
    'Next Step' => 'الخطوة التالية',
    'No' => 'لا',
    'No Title Set' => '',
    'Not enough credit to make the purchase' => '',
    'Note' => 'ملاحظة',
    'Order Summary' => '',
    'Review & Post Job' => '',
    'Save as Draft' => 'حفظ كمسودة',
    'Select All Universities' => '',
    'Select Language Level' => '',
    'Select Universities' => '',
    'Select Year' => '',
    'Select a Degree' => '',
    'Select as many as you\'d like' => '',
    'Selected language does not exist.' => '',
    'Selected major does not exist.' => '',
    'Selected nationality does not exist.' => '',
    'Selected university does not exist.' => '',
    'Step 1: Basic Details' => 'خطوة ١: التفاصيل الأساسية',
    'Step 2: Interview Questions' => 'خطوة ٢: أسئلة المقابلة',
    'Step 3: Choose which students can see your job listing' => 'خطوة ٣: اختيار من يمكن أن يرى فرصة عملك',
    'Step 4: Review your listing' => 'خطوة ٤: مراجعة تفاصيل الوظيفة',
    'This job listing will be taken down once you receive this number of applicants' => '',
    'Tip' => '',
    'Universities' => '',
    'Yes' => 'نعم',
    'You may purchase credit in advance for faster job posting' => '',
    'You will not be able to change these filters once you publish your job posting' => '',
    'Your Order' => '',
    'cost per applicant' => '',
    'maximum applicants' => '',
    'Applied' => 'مهتم',
    'Audience Targetting' => 'الجمهور المستهدف',
    'Basic cost per applicant is {0, number, 0.000} KD' => 'التكلفة الأساسية لكل متقدم {0, number, 0.000} د.ك.',
    'Closed' => 'مغلق',
    'Dashboard' => 'لوحه التحكم',
    'Don\'t have an account? <a href=\'{url}\'>Register</a>' => 'ليس لديك حساب؟ <a href=\'{url}\'>سجل</a>',
    'Drafts' => 'مسودات',
    'Each option increases applicant cost by {0, number, 0.000} KD' => 'التكلفة الأساسية لكل فلتر {0, number, 0.000} د.ك.',
    'If you forgot your password you can' => 'إذا كنت قد نسيت كلمة المرور الخاصة بك يمكنك ',
    'KD' => 'د.ك.‏',
    'Login' => 'تسجيل الدخول',
    'New password was saved.' => 'تم حفظ كلمة المرور الجديدة.',
    'Open' => 'مفتوح',
    'Password reset link sent, please check your email for further instructions.' => 'تم ارسال الرابط الى إعادة تعيين كلمة المرور، يرجى التحقق من بريدك الالكتروني لمزيد من التعليمات.',
    'Pending' => 'انتظار',
    'Please choose your new password' => 'يرجى اختيار كلمة مرور جديدة',
    'Please click the verification link sent to you by email to activate your account.<br/><a href=\'{resendLink}\'>Resend verification email</a>' => 'الرجاء الضغط على الرابط الذي أرسل لك عن طريق البريد الإلكتروني لتفعيل حسابك. <br/> <a href=\'{resendLink}\'> إعادة إرسال</a> البريد الإلكتروني',
    'Please fill out the following fields to login' => 'يرجى ملء الحقول التالية للدخول',
    'Please fill out your email. A link to reset password will be sent there' => 'يرجى ملء البريد الإلكتروني الخاص بك. سيتم إرسال رابط لإعادة تعيين كلمة المرور',
    'Post a Job Opening' => 'إضافة عرض الوظيفة',
    'Premium Filters' => 'فلاتر متميزة',
    'Request password reset' => 'طلب إعادة تعيين كلمة المرور',
    'Reset password' => 'إعادة تعيين كلمة المرور',
    'Save' => 'حفظ',
    'Send' => 'إرسال',
    'Sorry, we are unable to reset password for email provided.' => 'آسف، نحن غير قادرين على إعادة تعيين كلمة المرور للبريد الإلكتروني',
    'There is no employer with such email.' => 'لا يوجد صاحب العمل مع هذا البريد الإلكتروني.',
    'reset it' => 'إعادة تعيينها',
];
