<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'This job pays!' => 'هذا يدفع!',
    'Woohoo!' => 'ياي!',
    'Apply' => 'قدم',
    'Browse Jobs' => 'تصفح فرص العمل',
    'Contact' => 'إتصل بنا',
    'Employer Portal' => 'بوابة صاحب العمل',
    'Enrollment year must be before graduation year.' => 'يجب أن تكون سنة الالتحاق قبل سنة التخرج.',
    'Graduation year end must be greater than or equal to the graduation year start.' => 'يجب أن يكون في نهاية العام التخرج أكبر من أو تساوي السنة بداية التخرج.',
    'Home' => 'الرئيسية',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'إذا كان لديك استفسارات أو أسئلة، يرجى ملء النموذج التالي للاتصال بنا. شكرا.',
    'Invalid input for {attribute}' => 'إدخال غير صالح لل{attribute}',
    'Login' => 'تسجيل دخول',
    'Logout' => 'تسجيل الخروج',
    'Please upload a photo of your university id card' => 'يرجى تحميل صورة من بطاقة الهوية جامعتك',
    'Please use your university email eg: {emailName}@{universityDomain}' => 'الرجاء استخدام البريد الإلكتروني الجامعي الخاص بك على سبيل المثال: {emailName}@{universityDomain}',
    'Register' => 'تسجيل',
    'Selected language does not exist.' => 'لا وجود اللغة المحددة',
    'Selected major does not exist.' => 'عدم وجود هذا التخصص',
    'Student Portal' => 'بوابة الطالب',
    'The format of your date of birth is invalid, should be yyyy/mm/dd' => 'شكل تاريخ ميلادك غير صالح، ينبغي أن يكون شهر / يوم / سنة',
    'This city does not exist.' => 'لا وجود لهذه المدينة.',
    'This degree does not exist.' => 'عدم وجود هذه الشهادة',
    'This email address is already registered.' => 'هذا البريد الإلكتروني لديه حساب',
    'This email belongs to {universityName}' => 'هذا البريد الإلكتروني ينتمي إلى {universityName}',
    'This industry does not exist.' => 'لا وجود لهذا القطاع.',
    'This job type does not exist.' => 'عدم وجود هذا النوع وظيفة',
    'This nationality does not exist.' => 'عدم وجود هذه الجنسية',
    'This university does not exist.' => 'هذه الجامعة لا وجود لها',
    'University does not exist' => 'الجامعة لا وجود لها',
    'Work start date is' => 'تاريخ بدء العمل',
    'You must be at least {age} years old' => 'عمرك يجب ان يكون على الاقل {age} سنة',
    'Your CV upload is invalid' => 'تحميل السيرة الذاتية الخاصة بك غير صالح',
    'Your photo upload is invalid' => 'تحميل الصور الخاصة بك غير صالح',
    'flexible' => 'مرن',
];
