<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Invalid input for {attribute}' => 'إدخال غير صالح لل{attribute}',
    'Please upload a photo of your university id card' => 'يرجى تحميل صورة من بطاقة الهوية جامعتك',
    'Please use your university email eg: {emailName}@{universityDomain}' => 'الرجاء استخدام البريد الإلكتروني الجامعي الخاص بك على سبيل المثال: {emailName}@{universityDomain}',
    'Selected language does not exist.' => 'لا وجود اللغة المحددة',
    'Selected major does not exist.' => 'عدم وجود هذا التخصص',
    'The format of your date of birth is invalid, should be mm/dd/yyyy' => 'شكل تاريخ ميلادك غير صالح، ينبغي أن يكون شهر / يوم / سنة',
    'This email address is already registered.' => 'هذا البريد الإلكتروني لديه حساب',
    'This email belongs to {universityName}' => 'هذا البريد الإلكتروني ينتمي إلى {universityName}',
    'This university does not exist.' => 'هذه الجامعة لا وجود لها',
    'University does not exist' => 'الجامعة لا وجود لها',
    'You must be at least {age} years old' => 'عمرك يجب ان يكون على الاقل {age} سنة',
    'Your CV upload is invalid' => 'تحميل السيرة الذاتية الخاصة بك غير صالح',
    'Your photo upload is invalid' => 'تحميل الصور الخاصة بك غير صالح',
    'About' => 'من نحن',
    'Contact' => 'إتصل بنا',
    'Home' => 'الرئيسية',
    'Login' => 'تسجيل دخول',
    'Logout' => 'تسجيل الخروج',
    'Register' => 'تسجيل',
];
