<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Sign up and find a job today!' => 'اشترك واعثر على وظيفة اليوم',
    'Change' => 'تغيير',
    'Email Verified' => 'البريد الإلكتروني تم التحقق منه',
    'I\'d like my password to be' => 'أود كلمة المرور الخاصة بي لتكون',
    'Invalid email verification code' => 'غير صالح رمز التحقق للبريد الإلكتروني ',
    'My phone number is' => 'رقم هاتفي هو',
    'My university email is' => 'بريدي الإلكتروني للجامعة',
    'Next Step' => 'الخطوة التالية',
    'Only files with these extensions are allowed for CV: {extensions}' => 'يسمح فقط الملفات مع هذه الملحقات للسيرة الذاتية {extensions}',
    'Only files with these extensions are allowed for ID: {extensions}' => 'يسمح فقط الملفات مع هذه الملحقات لهوية الطالب {extensions}',
    'Only files with these extensions are allowed for your Photo: {extensions}' => 'يسمح فقط الملفات مع هذه الملحقات للصورة {extensions}',
    'Password' => 'كلمة المرور',
    'Phone Number' => 'رقم الهاتف',
    'Please upload a photo of your student ID card' => 'يرجى تحميل صورة من بطاقة هوية الطالب الخاص بك',
    'Registration' => 'تسجيل',
    'Remove' => 'حذف',
    'Select your University' => 'اختر جامعتك',
    'Sign Up' => 'سجل',
    'Student ID Verification' => 'التحقق من هوية الطالب',
    'Thank You!' => 'شكرا',
    'University not listed?' => 'جامعة غير مذكورة؟',
    'Upload ID Card' => 'تحميل بطاقة الهوية',
    'You may still sign up and our agents will get in touch with you for account activation.' => 'يمكنك التسجيل على الرغم من عدم وجود جامعتك لدينا وإن توفرت الفرصة سوف نقوم بالإتصال بك لتفعيل الحساب ',
];
