<?php
use yii\helpers\Url;

/* @var $this yii\web\View */
$this->title = Yii::t("frontend", "Terms & Conditions");
$this->params['breadcrumbs'][] = $this->title;

$this->registerCss(" 
.termsC ul li{list-style-type: upper-roman; margin-left:3em;}
");
?>

<div class="panel">
    <div class="panel-heading">
        <div class="panel-title">
            <h4><?= $this->title ?></h4>
        </div>
    </div>

    <div class="panel-body termsC">
        
        <div class="row">
            <p>
                Welcome to the StudentHub website, operated by BAWES - Built Awesome. (“BAWES”) and located at <a href='http://www.studenthub.co' target='_blank'>http://www.studenthub.co</a> (the “Site”). The Site is an online platform through which students at particular educational institutions seeking employment opportunities (each, a “Student”) can find and connect with providers of such employment opportunities (each, a “Business”).
            </p>
            <p>
                BAWES does not take part in, nor is BAWES in any way responsible for, any interactions between Students and Businesses, except to the extent necessary to maintain the Site. Any interaction between you and any other individual or entity through the Site or arising out of your use of the Site, including any interactions between Businesses and Students, is solely between you and that other individual or entity. BAWES expressly disclaims any responsibility for any interactions between Students and Businesses. For avoidance of doubt, BAWES disclaims any responsibility for any employment opportunities, employment services, or any other services or products acquired or made available through the Site, even if BAWES investigates or attempts to verify any information in connection therewith. You agree that you must evaluate and bear all risks associated with the use of the Site, including the Site Materials and the User Content, and that you may not rely on the Site Materials or User Content.
            </p>
            <p>
                The following terms and conditions (“Terms”) govern your use of the Site. By accessing, viewing, or using the content, material, or services available on or through this Site, you indicate that you have read and understand these Terms, that you agree to them and intend to be legally bound by them. If you do not agree to these Terms, you are not granted permission to use this Site and must exit immediately.
            </p>
            <p>
                <b>1. Registration.</b> In order to access certain content, services, products or benefits on the Site, you will be asked to register and create an account. By registering an account on the Site, you represent that you are 18 years of age or older, or you have your parents permission to use the Site. Depending on your intended uses of the Site, you may be asked to designate your account as either a Student Account (i.e., for a Student) or a Business Account (i.e., for a Business). Your obligations and rights under these Terms may vary depending on whether you registered as a Student or a Business. Also as part of the registration process, you may be asked to input an email and a password, and may be required to provide BAWES with certain information about yourself, including some types of personally identifying information such as your email and your employer or educational institution. You agree that the information that you provide to us on registration and at all other times will be true, accurate, current and complete. You also agree that you will ensure that this information is kept accurate and up to date at all times. Any information that you provide to BAWES through the Site or email is subject to <a href='<?= Url::to(['site/privacy-policy']) ?>' target='_blank'>BAWES' Privacy Policy</a>, which is hereby incorporated into these Terms by reference as if set forth fully herein.
            </p>
            <p>
                As part of the registration process, you will be asked to input your email and a password. Only you are permitted to access the Site, the Site Materials, and the User Content through your account. Without limiting the foregoing, you are fully responsible for your account, including use of the account by any third party, and maintaining the confidentiality of your password. You may suspend your account at any time by emailing us on <a href='mailto:contact@studenthub.co'>contact@studenthub.co</a>.
            </p>
            <p>
                By registering, you are subscribing to transactional notification emails that will inform you when a job that matches your profile is posted. You can unsubscribe or manage your notification frequency settings at any time from these emails by logging into your account and changing your notification settings.
            </p>
            <p>
                <b>2. Verification.</b> By registering with the Site, you hereby authorize BAWES to verify any representations and warranties you make either pursuant to these Terms or within any materials submitted during the registration process, including conducting background checks, contacting any provided references, and reviewing public records. You acknowledge that while BAWES reserves the right to verify these representations and warranties, BAWES is not obligated to do so, and may choose not to do so, in BAWES' sole discretion.
            </p>
            <p>
                <b>3. Listing Employment Opportunities.</b> Upon registration, a Business may submit, through the Site, a notification to Students of a potential employment opportunity (a “Job Posting”). A Job Posting may only notify Students of a single employment opportunity, and must include, at a minimum, the following information: position title and job description. Upon submission of a Job Posting, the submitting Business may fix typographical errors within the Job Posting, but may not make any substantial changes to the Job Posting.
            </p>
            <p>
                You agree not to use the Site to promote or further the commercial activities, including by submitting a Job Posting in connection with those activities, of any of the businesses, activities, or practices set forth in BAWES' list of Prohibited Business, as incorporated into these Terms by reference as if set forth fully herein. For avoidance of doubt, each Job Posting must comply with all restrictions hereunder, including those governing the submission of User Content and general use of the Site. BAWES may, but is not obligated to, make an independent investigation of the Job Posting to ensure full compliance with these Terms. If BAWES determines, in its sole discretion, that any representation or warranty made by you pursuant to these Terms is in any way false, incomplete, or inaccurate, BAWES may, at any time, reject, remove, or suspend or delay the posting of your Job Posting, in whole or in part. BAWES may, but is not obligated to, provide you with an explanation for the rejection or removal of any of your Job Postings from the Site.
            </p>
            <p>
                All jobs posted on StudentHub will be automatically transferred into a publicly-viewable job listing page. These pages are indexed to Google, and are not taken down after being filled; however, the job page will not accept applicants once a listing is closed (and the page will act as informational only, with links bringing a user back to the StudentHub default homepage.)
            </p>
            <p>
                <b>4. Payment and Cancellation.</b> Some products or services on the Site, including the opportunity for a Business to post an employment opportunity, will be available for purchase. You are responsible for all charges incurred under your account, whether made by you or another person using your account. If for any reason BAWES does not receive payment for a purchase, BAWES may exercise its rights in law and equity, including (a) immediately suspending or terminating your account; (b) seeking collection of the outstanding amount owed; and/or (c) seeking legal action against you for the breach of these Terms. You are also responsible for paying any governmental taxes imposed in connection with use of the Site or the purchase or any products or services, including sales, use, and excise taxes (excluding only taxes on BAWES' net income). To the extent that BAWES is obligated to collect such taxes, the applicable tax will be added to your billing account. All sales are final. BAWES is not responsible for any costs or expenses in connection with any interactions between Students and Businesses.
            </p>
            <ul>
                <li>
                    <b>Services:</b> Different premium services are purchased and accessed from different pages on <a href='http://studenthub.co' target='_blank'>studenthub.co</a>. All prices are in Kuwaiti Dinar.
                </li>
                <li>
                    <b>Payment:</b> All amounts payable by Customer must be received in full prior to commencement of Service. Customer will be responsible for the payment of any present or future sales, use, excise applicable to the services hereunder. Amounts paid hereunder are non-refundable.
                </li>
                <li>
                    <b>Cancellations and Refunds:</b> All requests for refunds will be reviewed on a case by case basis and awarded at BAWES’ sole discretion. All approved refunds will be made in the form of credit that can be used on the platform for additional purchases.
                </li>
                <li>
                    <b>Credit Card Information:</b> The details collected do not include credit card details of customers. All credit card information will not be stored, sold, shared, rented or leased to any third parties.
                </li>
            </ul>
            <p>
                <b>5. Proprietary Rights.</b> Unless BAWES explicitly states otherwise in an agreement between you and BAWES, as between you and BAWES, BAWES owns or licenses all data, content, graphics, forms, artwork, images, photographs, functional components and any software concepts and documentation and other material on, in or made available through the Site (“Site Materials”), as well as the selection, coordination, arrangement, and organization and enhancement of the Site Materials. All Site Materials are protected pursuant to copyright, trademark, patent and other applicable laws. As between any user of the Site and BAWES, all names, trademarks, service marks, certification marks, symbols, slogans or logos appearing on the Site are proprietary to BAWES or its affiliates, licensors (including Businesses), or suppliers. Use or misuse of these trademarks is expressly prohibited and may violate federal and state trademark law. Under no circumstances will you have any rights of any kind in or to the Site Materials, other than the right to use the Site Materials in accordance with these Terms.
            </p>
            <p>
                Certain features of the Site (including the registration processes described in Section 1 above) may allow you to contribute comments, feedback, information, content, text, files, trademarks, logos, graphics, postings, and other materials and information, including Job Postings, for access, use, viewing and commentary by other users to the Site (“User Content”). By posting User Content, you represent that you have the full legal right to provide the User Content and that use of the User Content by the Site and all other persons and entities will not: (a) infringe any intellectual property rights of any person or entity or any rights of publicity, personality, or privacy of any person or entity, including as a result of your failure to obtain consent to post personally identifying or otherwise private information about a person; (b) violate any law, statute, ordinance, regulation, or agreement; (c) be defamatory, libelous or trade libelous, unlawfully threatening, or unlawfully harassing; (d) impersonate any person or entity or falsely state or otherwise imply an affiliate with a person or entity, including any business or educational institution, or that is generally false, deceptive, misleading, deceitful, misinformative, or constitutes a “bait and switch”; (e) be obscene, child pornographic, or indecent; (f) violate any community or Internet standard; (g) constitute misappropriation of any trade secret or know-how; or (i) constitute disclosure of any confidential information owned by any third party.
            </p>
            <p>
                You retain all right, title and interest in and to the User Content that you submit and all intellectual property rights embodied therein. Upon your submission of User Content or other material or information to BAWES, you grant BAWES a worldwide, perpetual, irrevocable, transferable, license to access, use, distribute, reproduce, display, modify, create derivative works based upon, and sublicense, the User Content, all without any compensation to you whatsoever. If you believe that any content or postings on the Site or the Application violate your intellectual property or other rights, please follow our Complaint Procedure in Section 12 of these Terms.
            </p>
            <p>
                <b>6. Unauthorized Activities.</b> You agree that you will not use the Site for: (a) any illegal or unauthorized purposes that violate any local, national, or international laws (including but not limited to import, export, copyright, and trademark laws); (b) contacting any other user of the Site who has requested not to be contacted; (c) stalking or harassing anyone; (d) data mining, scraping, or for releasing spiders, robots, web crawlers, or any other data gathering or extraction tools to collect any information from the Site, including any information related to the Job Postings, except to the extent the Site is indexed by general purpose public search engines; (e) promoting any effort to compete with BAWES, including using the Site to provide, alone or in combination with any other product or service, any service to any third party or any use that causes a reduction or loss of business for BAWES as related to an existing or potential customer; (f) modifying, copying, distributing, displaying, performing, reproducing, publishing, licensing, creating derivative works from, transferring, selling any of the Site Materials, unless otherwise authorized by these Terms or in a separate written agreement with BAWES; (g) attempting to gain unauthorized access to BAWES' computer system or engaging in any activity that interferes with the performance of, or impairs the functionality of the Site or any services provided through the Site; (h) any resale or commercial use of the Site, the Site Materials, or the User Content; (i) using the Site to access or collect any personally identifiable information, including any names, email addresses or other such information for any purpose, including any commercial purposes; (j) violating or offending any community or Internet standards of decency; or (k) removing, circumventing, disabling, damaging or otherwise interfering in any way with any security features of the Site aimed at preventing or restricting the unauthorized use of the Site or any of the Site Materials. You may only use the Site and the Site Materials consistently with these Terms. Any other use of the Site or Site Materials, including but not limited to the aforementioned unauthorized uses, without prior written permission of BAWES is strictly prohibited. You acknowledge and agree that the unauthorized use of the Site or the Site Materials could cause irreparable harm to BAWES and that in the event of such unauthorized use, BAWES shall be entitled to an injunction in addition to any other remedies available at law or in equity.
            </p>
            <p>
                <b>7. Third Party Web Sites and Content.</b> The Site is available for informational purposes only. BAWES is a private company, and is not affiliated with any Business or educational institution, including any university or college. The Site may contain links to other Internet Web sites for the convenience of users in locating information, products, or services that may be of interest. The Site may also incorporate features and services provided by third parties, such as payment processing. Use of such third party links, features, and services, the Site and the Site Materials, and any other material or content on and made available through the Site is entirely at your own risk. BAWES does not recommend and expressly disclaims any responsibility for the content, the accuracy of the information, or quality of products or services provided by or advertised on third party sites or the transactions you conduct or enter into with third parties. Your use of any third party’s website is at your own risk, and subject to the terms and conditions of such other websites, including the terms and conditions of BAWES' third party payment processors. BAWES does not endorse any product, service, or treatment provided on a third party website or advertised or provided on the Site.
            </p>
            <p>
                <b>8. Availability of the Site.</b> BAWES uses reasonable efforts to ensure that the Site is generally available. However, there will be occasions when access to the Site will be interrupted or unavailable. BAWES will use reasonable efforts to minimize such disruption where it is within its reasonable control. You agree that BAWES shall not be liable any modification, suspension, or discontinuance of the Site and that all amounts paid under these terms are non-refundable.
            </p>
            <p>
                THE COMPANY DOES NOT WARRANT THAT THE WEB SITE WILL OPERATE ERROR-FREE OR THAT THE WEB SITE AND ITS SERVER (OR ANY SOFTWARES AND MATERIALS ACCESSIBLE THROUGH THE WEB SITE) ARE FREE OF COMPUTER VIRUSES OR OTHER HARMFUL MECHANISMS. IF YOUR USE OF THE WEB SITE OR THE MATERIAL RESULTS IN THE NEED FOR SERVICING OR REPLACING EQUIPMENT OR DATA, THE COMPANY IS NOT RESPONSIBLE FOR THOSE COSTS.
            </p>
            <p>
                <b>9. Disclaimer.</b> The information on this Site is for informational purposes only. Without limiting anything else in these Terms or otherwise, BAWES is not responsible for any errors or omissions in the Site or Site Materials. BAWES, its subsidiaries, and affiliates, are not responsible for and do not guarantee the accuracy or completeness of any Site Materials, User Content, products, data, services (whether performed by BAWES, any Student or Business, or any third party), links, advertisements, or other items contained within the Site. BAWES reserves the right to immediately remove any Site Materials or User Content for any reason or for no reason. BAWES cannot and does not review all communications or products made available on or through the Site, but, although not obligated to, may review, verify, make changes to or remove any User Content, Site Materials, the Site or the products or services made available in connection with the Site, including information submitted in connection with the Site Materials or other features at any time, with or without notice in its sole discretion.
            </p>
            <p>
                THE SITE, THE SITE MATERIALS, USER CONTENT, SERVICES, PRODUCTS, INFORMATION, AND OTHER MATERIALS ON, IN AND MADE AVAILABLE THROUGH THE SITE ARE MADE AVAILABLE “AS IS” AND “WITH ALL FAULTS.” USE OF THE SITE IS ENTIRELY AT YOUR OWN RISK. BAWES AND ITS LICENSORS MAKE NO REPRESENTATIONS OR WARRANTIES, AND DISCLAIM ALL REPRESENTATIONS AND WARRANTIES, WITH RESPECT TO THE SITE, THE USER CONTENT, THE SITE MATERIALS, SERVICES, PRODUCTS, DATA AND OTHER MATERIALS ON, IN AND MADE AVAILABLE THROUGH THE SITE, EXPRESS OR IMPLIED, WRITTEN OR ORAL, ARISING FROM COURSE OF DEALING, COURSE OF PERFORMANCE, USAGE OF TRADE, OR OTHERWISE, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, SYSTEMS INTEGRATION, NON-INTERFERENCE, QUALITY, TITLE, AND NON-INFRINGEMENT. THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY, COMPLETENESS AND EFFORT WITH REGARD TO ANY USER CONTENT, THE SITE, THE SITE MATERIALS, SERVICES, PRODUCTS, DATA AND OTHER MATERIALS ON, IN AND MADE AVAILABLE THROUGH THE SITE, IS WITH YOU.
            </p>
            <p>
                <b>10. LIMITATION OF LIABILITY.</b> THE SITE AND MATERIAL ARE PROVIDED ON AN AS IS AND AS AVAILABLE BASIS WITHOUT ANY WARRANTIES OF ANY KIND. BAWES, TO THE FULLEST EXTENT PERMITTED BY LAW, DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, THE WARRANTY OF MERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. THE COMPANY MAKES NO WARRANTIES ABOUT THE ACCURACY, RELIABILITY, COMPLETENESS, OR TIMELINESS OF THE MATERIAL, SERVICES, SOFTWARE, TEXT, GRAPHICS, AND LINKS. 
BAWES AND ITS LICENSORS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY, EXTRA-CONTRACTUAL, OR PUNITIVE DAMAGES OF ANY KIND WHATSOEVER, INCLUDING LOST REVENUES OR LOST PROFITS, WHICH MAY OR DOES RESULT FROM THE USE OF, ACCESS TO, OR INABILITY TO USE THE SITE, THE USER CONTENT, THE SITE MATERIALS, SERVICES, PRODUCTS, DATA AND OTHER MATERIALS ON, IN AND MADE AVAILABLE THROUGH THE SITE, REGARDLESS OF LEGAL THEORY, WHETHER OR NOT YOU OR BAWES HAD BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES, AND EVEN IF THE REMEDIES OTHERWISE AVAILABLE FAIL OF THEIR ESSENTIAL PURPOSE. UNDER NO CIRCUMSTANCES WILL THE TOTAL LIABILITY OF BAWES AND ITS LICENSORS TO YOU OR ANY OTHER PERSON OR ENTITY IN CONNECTION WITH, BASED UPON, OR ARISING FROM THE SITE, USER CONTENT, THE SITE MATERIALS ON, IN AND MADE AVAILABLE THROUGH THE SITE, OR THE SERVICES, PRODUCTS, DATA OR OTHER MATERIALS OFFERED IN CONNECTION THEREWITH EXCEED THE PRICE PAID BY YOU DURING THE PRECEDING YEAR FOR USE OF THE SITE AND THE SERVICES AND PRODUCTS. SOME COUNTRIES DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IF ANY PART OF THIS LIMITATION ON LIABILITY IS FOUND TO BE INVALID OR UNENFORCEABLE FOR ANY REASON, THEN THE TOTAL LIABILITY OF BAWES AND ITS LICENSORS SHALL NOT EXCEED TEN DOLLARS ($10). If you are dissatisfied with the Site or with any of these Terms, or feel BAWES has breached these Terms, your sole and exclusive remedy is to discontinue using the Site.
            </p>
            <p>
                <b>11. Indemnification.</b> You shall indemnify BAWES and its directors, officers, employees, agents, contractors and licensors (“BAWES Indemnitees”) against all claims, actions, suits, and other proceedings (each, a “Claim”) arising out of or incurred in connection with the Site and your use of the Site, the Site Materials or any services, product or data obtained through the Site, your fraud, violation of law, negligence, willful misconduct, or any other use of the Site, the User Content, the Site Materials, the services, products, information and other materials on, in and made available through the Site, except to the extent attributable to BAWES, or any breach by you of these Terms and shall indemnify and hold BAWES Indemnitees harmless from and against all judgments, losses, liabilities, damages, costs, and expenses (including reasonable attorneys’ fees and attorneys’ disbursements) arising out of or incurred in connection with such Claims. You may not settle any Claim without the prior written consent of BAWES. BAWES or its licensors may assume the defense of any Claim, at your sole cost and expense, and you shall cooperate in all reasonable respects in such defense. You shall have the right to employ separate counsel in any Claim and to participate in the defense thereof. If BAWES or its licensors do not notify you that it elects to undertake the defense thereof, you shall have the right to defend the Claim with counsel reasonably acceptable to BAWES, subject to the right of BAWES to assume, at their sole cost and expense, the defense of any Claim at any time prior to the settlement or final determination thereof.
You agree to defend, indemnify, and hold harmless BAWES, its officers, directors, employees and agents, from and against any claims, actions or demands, including without limitation reasonable legal and accounting fees, alleging or resulting from your use of the Material or your breach of the terms of these Terms and Conditions or your representations and warranties or your violation of any rights of third parties, including without limitation, any proprietary or intellectual property rights.
            </p>
            <p>
                <b>12. Complaint Procedures.</b> If you believe that any content or postings on this Site violates your intellectual property or other rights, please notify BAWES by email at <a href='mailto:contact@studenthub.co'>contact@studenthub.co</a> a comprehensive detailed message setting forth the following information: (a) your name and the name of your company, if any; (b) your contact information, including your email address; (c) the nature and substance of your complaint, the specific rights at issue, and your basis for making the complaint, including the content or posting that is objectionable; and (d) the following statement: “The statements, representations, and assertions made in this message are true, complete, and accurate and I have the full legal authority to make each and every such statement, representation, and assertion and to make and be granted any demand made in this message.”
            </p>
            <p>
                <b>13. Changes to these Terms; Termination.</b> BAWES reserves the right at any time to modify, alter, or update these Terms. Your use of the Site following any changes means that you agree to follow and be bound by the terms as changed. Any change to these Terms shall be effective as to any visitor who has visited the Site before the change was made. It is the obligation of users visiting the Site before the change to learn of changes to the Terms since their last visit. BAWES may suspend or terminate your account and/or your ability to use the Site, or any services on the Site, for failure to comply with these Terms, for inactivity on the Site, for providing BAWES with untrue or inaccurate information about yourself, for infringement upon BAWES proprietary rights, or for any other reason whatsoever or for no reason.
            </p>
            <p>
                <b>14. Relationship Between the Parties.</b> Nothing in these Terms shall be construed as making either party the partner, joint venturer, agent, legal representative, employer, contractor, or employee of the other.
            </p>
            <p>
                <b>15. Governing Law and Jurisdiction.</b> These Terms represent the entire agreement between you and BAWES with respect to the subject matter hereof, and supersede all prior and contemporaneous written and oral representations, understandings, and agreements, express and implied, and will be governed by and construed in accordance with the laws of Kuwait, without reference to its conflict of law rules; PROVIDED, HOWEVER, THAT THE TERMS OF ANY APPLICABLE LAW NOW OR HEREAFTER ENACTED THAT IS BASED ON, DERIVED FROM, SIMILAR TO, OR CONNECTED WITH THE UNIFORM COMPUTER INFORMATION TRANSACTIONS ACT DRAFTED BY THE NATIONAL CONFERENCE OF COMMISSIONERS ON UNIFORM LAWS SHALL NOT APPLY EXCEPT TO THE EXTENT THAT THE LAW EXPRESSLY PROHIBITS ALTERATION BY THESE TERMS OF THE APPLICABILITY OF ONE OR MORE SECTIONS OF THE LAW. By accessing, viewing, or using the services, works, content, or materials on the Site, you consent and agree to (a) the exclusive jurisdiction of the courts located in Kuwait; (b) accept service of process by personal delivery or mail; and (c) irrevocably waive the right to trial by jury and any jurisdictional and venue defenses otherwise available.
            </p>
            <p>
                <b>16. Miscellaneous.</b> The Site is controlled and operated from within Kuwait. Without limiting anything else, BAWES makes no representation that the Site, Site Materials, User Content, services, products, information or other materials available on, in, or through the Site is appropriate or available for use in other locations, and access to them from territories where they are illegal is prohibited. Those who choose to access the Site from other locations do so on their own volition and are responsible for compliance with applicable laws. The waiver or failure of BAWES to exercise in any respect any right provided hereunder shall not be deemed a waiver of such right in the future or a waiver of any of other rights established under these Terms. Headings used in these Terms are for reference only and shall not affect the interpretation of these Terms. No person or entity not party to this agreement will be deemed to be a third party beneficiary of these Terms or any provision hereof. When used herein, the words “includes” and “including” and their syntactical variations shall be deemed followed by the words “without limitation.”
            </p>
            <p>
                Dated:  August 30, 2015<br/>
                If you need to contact us, we recommend you reach out to <a href='mailto:contact@studenthub.co'>contact@studenthub.co</a>.<br/>
                Copyright © 2015 BAWES; All rights reserved.
            </p>
            
        </div>
    </div>

</div>
